services:
  - type: web
    name: smart-blind-stick
    runtime: python
    plan: free

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python app.py

    healthCheckPath: /health

    envVars:
      - key: PYTHON_VERSION
        value: 3.12.9

      - key: RENDER
        value: "true"

      - key: MONGO_URI
        sync: false