services:
  - type: web
    name: smart-blind-stick
    env: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.11.0
